### ISSUE TITLE
Configuration design: Wrong format: list vs mapping

### ISSUE THREAD

**Issue by malex984** [hilbert/hilbert-cli#17]
Note: this is a separation of super-issue hilbert/hilbert-cli#13

**General: 1.2** The format is wrong. If you want to list people you do:

```
- name: john
  phone: 5411-2222
- name: peter
  phone: 3838-1111
```

or

```
john:
  phone: 5411-2222
peter:
  phone: 3838-1111
```

not

```
- john:
  phone: 5411-2222
- peter:
  phone: 3838-1111
```

because that is equivalent to

```
[
  {john: 
    {phone: 5411-2222}
  },
  {peter:
    {phone: 3838-1111}
  }
]
```

**Comment by porst17** [comment]
Is this still under discussion? To me,

```
john:
  phone: 5411-2222
peter:
  phone: 3838-1111
```

seems to be the way to go, i.e. you would define the IDs `john` and `peter` in the map that can then be used elsewhere.
